//UserAPI requests
//read all users
GET http://localhost:3000/userAPI/users


###
GET http://localhost:3000/userAPI/users/697f1d179eaf421da5c7a256

//create user
###
POST http://localhost:3000/userAPI/users
Content-Type: application/json

{
    "username":"Hema",
    "password":"sau@123456",
    "age":23
}

###
PUT http://localhost:3000/userAPI/users/697f1f298259c69e10c54103
Content-Type: application/json

{
    "username":"nithin",
    "password":"nithin6546",
    "age":20
}

###
DELETE http://localhost:3000/userAPI/users/697f1f298259c69e10c54103



# =========================================================================

//prodcut API requests

//get all the users
###
GET http://localhost:3000/productAPI/products

//creates user
###
POST http://localhost:3000/productAPI/products
Content-Type: application/json

{
    "pid":103,
    "productName":"pro",
    "price":5000000
}

//get user by objId
###
GET http://localhost:3000/productAPI/products/697dcfeb0267a73f04c52884

###
PUT http://localhost:3000/productAPI/products/697dcfeb0267a73f04c52884
Content-Type: application/json

{
    "pid":108,
    "productName":"Laptop",
    "price":50000
}

###
DELETE http://localhost:3000/productAPI/products/697dcfeb0267a73f04c52884